### ISSUE TITLE
Spinning 'Save Changes' button

### ISSUE THREAD

**Issue by westjr** [ClayCountyBCC/ClayFinancial#1]
When using the edit field functionality of the UI, after making all of the changes necessary then clicking save, the button is continually spinning. Closed the modal by clicking outside of it's bounds. The data was saved correctly. 

Possible issues:
- Browser issue:
  - If user was using IE, the function used to stop the button from displaying the spinning icon does not work as intended without a workaround. 
- Back-end:
  - Data is not formatted correctly when returned to the client.

**Comment by dmcbcc** [comment]
This was fixed and was caused by an out of sync client side UI.  It is not happening at this time on DV10 (tested), and should not be happening on Production.
